### ISSUE TITLE
Microservicio frontend: Componente Visualización de documento

### ISSUE THREAD

**Issue by salimvzqz** [SvS30/powerstreet-backend#10]
Subcomponente en el frontend, perteneciente a **Microservicio frontend: Administración de documentos** y del componente #13 

- [x] Debe mostrar el documento obtenido desde el menú izquierdo, si desde el menú izquierdo se dio clic en nuevo entonces este debe mostrar un textarea vacío.
- [x] La data proviene del #3.
- [x] Si se da clic a Editar desde #9 se debe ocultar la vista compilada del documento y mostrar el textarea antes mencionado, pero con el documento markdown sin compilar para que el usuario pueda modificarlo.
- [x] Cuando el usuario de clic a Guardar desde #9 se debe de quitar el textarea y mostrar el documento guardado compilado en HTML. Esta opción sirve tanto para los nuevos documentos como para los que ya se encontraban en la base de datos y se están editando.
- [x] Cuando el usuario de clic en Cancelar desde #9, se debe de quitar el textarea y limpiar todas las variables para que muestre el documento compilado que se tenía previamente antes de la edición.
