### ISSUE TITLE
Microservicio frontend: Componente Documento

### ISSUE THREAD

**Issue by salimvzqz** [SvS30/powerstreet-backend#13]
Componente en el frontend, perteneciente a **Microservicio frontend: Administración de documentos**.

- [x] En la parte superior debe tener el componente #9
- [x] En la parte central debe tener el componente #10
- [x] En la parte inferior debe tener el componente #11
