### ISSUE TITLE
Microservicio frontend: Componente busqueda de documentos

### ISSUE THREAD

**Issue by salimvzqz** [SvS30/powerstreet-backend#8]
Componente en el frontend, perteneciente a **Microservicio frontend: Administración de documentos**.

- [x] Usando endpoints de #4.
- [x] El componente debe mostrar un máximo de 5 registros en pantalla.
- [x] El componente debe contar con un buscador, este debe de buscar cada vez que se teclee algo buscando con las coincidencias de la palabra que contenga lo que se escribió en el buscador.
- [x] Al darle clic a algún título este debe cargar #13 con los datos del documento perteneciente a el título.
- [x] El menú debe contar con la opción nuevo documento que al darle clic, se cargara #13 sin ningún documento cargado.
