### ISSUE TITLE
Microservicio frontend: Componente administración documento

### ISSUE THREAD

**Issue by salimvzqz** [SvS30/powerstreet-backend#9]
SubComponente en el frontend, perteneciente a **Microservicio frontend: Administración de documentos** y del componente #13.

- [x] Si se seleccionó la opción nuevo debe tener la opción de cargar para poder subir un archivo desde la pc con #2
- [x] Opción de editar documento actual.
- [x] La opción de Guardar si se está editando desde un textarea del #10 y usar el #5
- [x] Opción cancelar para restablecer el documento actual #10
